version: '3.2'

services: 
    db:
        hostname: mysql
        image: mysql:5.7.31
        restart: always
        ports: 
            - 3307:3306
        volumes:
            - ./mysql/data:/var/lib/mysql
        environment: 
            MYSQL_ROOT_PASSWORD: `1q2w3e4r
            MYSQL_USER: seongho
            MYSQL_PASSWORD: `1q2w3e4r
            MYSQL_DATABASE: db
